### PR TITLE
Add conditional functions

### PR DESCRIPTION
**Pull request by crstauf**
A few conditional functions that are cool (IMO) but were missing from QM.

`wp_is_site_protected_by_basic_auth()` may be more appropriate for the Environment panel.

### CODE REVIEW

**Comment by johnbillion** [comment]
Thanks! To be honest the only one of these which is really a conditional is `is_login()`, so yes let's add that please. `is_local_attachment()` requires a `$url` parameter.

**Comment by johnbillion** [comment]
Not sure what's up with the test failures, I'll take a look.

**Comment by crstauf** [comment]
Agh, missed that (re: `is_local_attachment()`).

I do really like `is_protected_endpoint()`, and think it could be valuable in some cases. Is there somewhere better for that to go?

**Comment by crstauf** [comment]
Moved `wp_is_site_protected_by_basic_auth()` to Environment panel.

**Comment by crstauf** [comment]
Hmm, I don't recall closing this; will re-open. 🤷‍♂️

**Pull request closed without merging**
