### PR TITLE
Test Actions

### PR DESCRIPTION
**Pull request by johnbillion**
Figuring out whether Actions will run in a branch or not.

### CODE REVIEW

**Comment by crstauf** [comment]
Result?

**Comment by johnbillion** [comment]
Yep they do. Strangely all the checks get hidden once you close the PR.

**Comment by johnbillion** [comment]
https://github.com/johnbillion/query-monitor/actions

**Comment by johnbillion** [comment]
Ah no they still appear in the Checks tab on the PR.

**Pull request closed without merging**
