### PR TITLE
Log and display user capability checks

### PR DESCRIPTION
**Pull request by johnbillion**
This introduces a new panel which shows user capability checks that have been performed during the current page load.

The panel is quite noisy at the moment as it includes all cap checks from both the admin menu and the admin toolbar, which I think need filtering out by default.

Needs some thorough testing.

screen shot 2017-10-18 at 13 53 37

### CODE REVIEW

**Comment by Mte90** [comment]
I am trying but seems that the table width in my case is more bigger than the others tables.

**Comment by johnbillion** [comment]
I've switched this panel to use the collapsed view for the caller column. Greatly reduces the space that it takes up.

screen shot 2017-10-18 at 17 07 06

**Comment by johnbillion** [comment]
The cap check result and any arguments which were passed are now shown too.

If any cap check is performed against another user (eg. with `user_can( ... )`) then an extra column shows up which shows the user ID.

**Comment by shadyvb** [comment]
Can't thank you enough for this, been doing this manually, and painfully, for so long!

**Pull request merged**
