### PR TITLE
Adding option to track php functions time with adding actions in the …

### PR DESCRIPTION
**Pull request by ivdimova**
…code that will be profilled
For #282

### CODE REVIEW

**Comment by johnbillion** [comment]
Yep this is exactly the sort of thing I was thinking, thanks. A few points:

* The `QM_Timer` class can be used in place of manually calling `microtime()`. It supports starting, lapping, and stopping a timer and includes the time and memory usage. You can see this in use in the self-awareness output in the `develop` branch.
* Probably will need to handle timers that were started but not stopped, with a useful warning message.
* We'll need to consider overlapping timers. The `start` and `stop` properties in the collector might need to be converted to associative arrays keyed by the function name. Example that needs to be handled:

```php
do_action( 'qm/start', 'function_1' );
do_action( 'qm/start', 'function_2' );
...
do_action( 'qm/stop', 'function_1' );
do_action( 'qm/stop', 'function_2' );
```

**Comment by eddr** [comment]
Will you have to manually add "do_action" for each function you want to measure? if so, that's fine, but what about functions inside classes or if you want to get a measurement of the whole system at once?

**Comment by crstauf** [comment]
@eddr Interesting idea: a single location where you could add all of your timers, rather than having to manually add into each function/method. 

@johnbillion Possible to add `qm/start`/`qm/stop` onto a hook, and if there's no param (function name) provided, assume `current_action()`?

**Comment by johnbillion** [comment]
For now you'll need to manually call the actions (don't worry, I'm writing up some documentation for this feature), but some sort of automated measurements is a good idea and I'll look at it at a later date.

@crstauf Good idea, I like it. #309.

**Comment by crstauf** [comment]
@johnbillion has the documentation for these functions been created? I'm attempting to implement, but doesn't look like lapping is being displayed in the output?

**Comment by crstauf** [comment]
Addressed in https://github.com/johnbillion/query-monitor/issues/337#issuecomment-387065076

**Pull request merged**
