### PR TITLE
Fix PHPDoc

### PR DESCRIPTION
**Pull request by szepeviktor**
Discovered by @phpstan

### CODE REVIEW

**Comment by johnbillion** [comment]
Thanks.

What's the rule about `$this` as a parameter name for filters? I understand the reasoning (so implementations don't try to use a function parameter called `$this`) but it does mean the docblock parameter has a different name to the actual parameter.

**Comment by szepeviktor** [comment]
> it does mean the docblock parameter has a different name to the actual parameter.

Yes, `array()` is also named `$colletors`.
Docblocks list the **name** of the parameter, not its value.

**Comment by szepeviktor** [comment]
BTW To benefit from PHPStan you have to pay some little price.
But at the end paying these little prices end up to be beneficial too.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
