### PR TITLE
add column to asset outputter for script/stylesheet 'extra' data

### PR DESCRIPTION
**Pull request by crstauf**
implements feature request in #110 

screen shot 2016-07-22 at 4 16 57 pm

### CODE REVIEW

**Comment by johnbillion** [comment]
Thanks Caleb, I'll take a look at this next week.

**Comment by szepeviktor** [comment]
@johnbillion Could it be that weeks span 3 years :)

**Comment by johnbillion** [comment]
Coincidentally I was looking at this ticket last night, after working on improvements to the Scripts and Styles panels in the`develop` branch recently, and closing some old issues.

I'll leave this open for now but it will need refactoring. I do want to add a way of exposing the extra data associated with scripts and styles.

**Comment by lkraav** [comment]
@johnbillion btw I've been working on a "asset whitelist" plugin, and it would be really nice if I could easily highlight (red - blocked, or green - whitelisted) specific blocked asset identifier slugs somehow.

**Comment by johnbillion** [comment]
@ikraav QM does this for assets blocked by the Airplane Mode plugin, which works by converting the source URL into an `Airplane_Mode_WP_Error` object which is just a `WP_Error` object with a `__tostring()` method on it. You could do something similar. Does that help?

**Comment by crstauf** [comment]
@johnbillion @szepeviktor Updated the branch with `develop`, and added the column back.

**Comment by szepeviktor** [comment]
@johnbillion Maybe we are 11 click away from merge.

**Comment by crstauf** [comment]
I'll make the necessary adjustments to pass the tests this weekend.

**Comment by crstauf** [comment]
Fixes made.

**Comment by szepeviktor** [comment]
What a space! 👨‍🚀

**Pull request closed without merging**
