### PR TITLE
Switch to a web component

### LINKED ISSUE #591: Styling issue on long file path references
Styling issue on long file paths:
image
In this case wpml string translation plugin.

### LINKED ISSUE #673: Issue with QM table styles
I ran in to an issue where my theme CSS rules for tables override QM styles and tables become unreadable when using dark theme. My CSS rules affecting the tables are
```
thead, tbody, tfoot {
	border: 1px solid #f1f1f1;
	background-color: #fefefe;
}
tbody tr:nth-child(2n) {
	border-bottom: 0;
	background-color: #f1f1f1;
}
```
Problem could be solved by adding these rules / declarations with a higher specificity to query-monitor.css

```
/* New rule */
#query-monitor-main table thead, 
#query-monitor-main table tbody, 
#query-monitor-main table tfoot {
	border: none;
	background-color: inherit;
}
```
and
```
#query-monitor-main .qm tr {
	border: none !important;
	background-color: inherit; /* New declaration */
}
```
The higher specificity (under #query-monitor-main) should prevent any themes from overriding the values and help keep QM interface properly styled.

### PR DESCRIPTION
**Pull request by johnbillion**
I've been hacking around with the idea of switching QM's output to a web component so its styles are isolated ~~and then I don't need to worry about forcibly overriding theme styles with `!important`~~. It's sort of working. Has promise. Not going to focus on this until I've switched to front end rendering though.

* Fixes #591
* Fixes #673

### CODE REVIEW

**Comment by lkraav** [comment]
> Has promise.

Yep, custom elements ftw. But unless you transpile to ES5, be sure to announce you're kicking IE11 and themsuch to the curb.

**Comment by johnbillion** [comment]
Yeah I need to look into a polyfill

**Comment by crstauf** [comment]
Would this mean that QM output would not occur in non-JS situations (ex: testing)?

**Comment by johnbillion** [comment]
Yep, although QM already requires JavaScript in order to work.

**Pull request closed without merging**
