### PR TITLE
Accessibility improvements

### PR DESCRIPTION
**Pull request by GaryJones**
See individual commits, as they explain the accessibility improvements contained in this PR.

### CODE REVIEW

**Comment by johnbillion** [comment]
Neato! I'll have a check through this shortly.

**Comment by GaryJones** [comment]
FWIW, I have absolutely no idea what the cause of those HHVM failures are.

Do you not allow HHVM to fail?

**Comment by johnbillion** [comment]
See #128 for the HHVM failures. I'm not allowing tests to fail on HHVM currently because ideally they shouldn't.

**Comment by johnbillion** [comment]
These changes, along with other improvements, went into 2.12.0.

**Pull request closed without merging**
