### PR TITLE
Add new qm/collect/silent_http_error_statuses filter to silence specific HTTP API requests that result in 400-500 HTTP status codes

### PR DESCRIPTION
**Pull request by pbiron**
this PR addresses #474 in a slightly different way from my previous PR.

### CODE REVIEW

**Comment by pbiron** [comment]
It applies the filter in `QM_Collector_HTTP::log_http_response()` and adds the results of the filter
to a new member of the HTTP "object" that QM stores.  Then in `QM_Collector_HTTP::process()` it checks that member to decide whether the request was an "error".

This allows plugins to bracket their calls to `wp_remote_request()` with `add_filter()`/`remove_filter()`, instead of adding the filter "globally" and then in their callback having to check the backtrace.

I've been using this approach in every version of QM since 3.4.0 (i.e., I've been applying this patch to my local copy of QM) and have not noticed it adversely affect QM.

**Comment by pbiron** [comment]
The wordpress-beta-tester plugin already hooks into the filter in this PR (see https://github.com/afragen/wordpress-beta-tester/blob/develop/src/WPBT/WPBT_Beta_RC.php#L255).   Of course, we can always change
that part of beta tester if, for example, you have a better way of achieving this goal.

**Comment by pbiron** [comment]
Here is a screenshot of beta tester without the PR applied.
qm-wp-beta-tester-without-pr-applied

And here is a screenshot with it applied.
qm-wp-beta-tester-with-pr-applied

**Comment by johnbillion** [comment]
Closing as per #474

**Pull request closed without merging**
