### PR TITLE
Scroll to top function

### PR DESCRIPTION
**Pull request by rene-hermenau**
Alt text

### CODE REVIEW

**Comment by ctalkington** [comment]
you can click in the admin bar blank area to achieve same thing.

**Comment by rene-hermenau** [comment]
@ctalkington Can you go into deep? This does not work for me. Please see yourself:
Alt text

**Comment by johnbillion** [comment]
@ctalkington Clicking the admin toolbar to go to the top only works on WordPress.com and, AFAIK, with the Jetpack plugin installed.

@rene-hermenau I've toyed with a few back-to-top methods in QM, but I've not liked any of them. See #63 for example.

My preferred method is to use the browser's back button. This has the added advantage that it returns you to your previous position on the page, not to the top.

**Comment by ctalkington** [comment]
@johnbillion i have a fresh dev/nightly site with no jetpack that indeed acts as described.

**Comment by ctalkington** [comment]
https://github.com/aaronjorbin/develop.wordpress/blob/37dfbef847bd5f4507b3855c24dd747f534e0c4d/src/wp-includes/js/admin-bar.js#L132-L140

**Comment by johnbillion** [comment]
Wow, this functionality has been in WordPress for four years and I've never seen it.

**Comment by rene-hermenau** [comment]
@ctalkington Wow, its working as described. Close it here

**Pull request closed without merging**
