### PR TITLE
Modify check for is_main_query

### LINKED ISSUE #333: PHP "Undefined index" notices firing for user queries
When viewing something like `wp-admin/users.php`, the plugin emits notices like:

```
Undefined index: is_main_query
```

This seems to be because the checks for `$row['is_main_query']` in `output/html/db_queries.php` assume that the index at least exists, which it doesn't in the case of a user query.

### PR DESCRIPTION
**Pull request by jacklenox**
Fixes #333.

### CODE REVIEW

**Comment by gmazzap** [comment]
Any news on this?

My logs are exploding with `"Undefined index: is_main_query"`...

**Comment by justnorris** [comment]
@johnbillion It'd be really great to get this merged in soon as it's causing a lot of unnecessary notices in the UI when PHP errors are displayed (like in the typical dev-environment)

**Comment by johnbillion** [comment]
I'm gonna get this fixed in 3.1 but probably by fixing the root cause instead.

@justnorris Can you confirm that you're using a plugin such as HyperDB, or another `wp-content/db.php` database dropin?

**Comment by justnorris** [comment]
Yeah, this is happening on VIP Go and I think it might have to do with the fact that VIP Go query collector is a bit out of sync with QM. I'm doing a diff on the files right now:

https://github.com/Automattic/vip-go-mu-plugins/blob/7ddbaeed75da5ae425ed79ba99c8e49edf9c7246/vip-helpers/vip-query-monitor.php

https://github.com/johnbillion/query-monitor/blob/master/collectors/db_queries.php

**Comment by johnbillion** [comment]
Ah yes that's most likely the cause, thanks.

**Comment by johnbillion** [comment]
See #333 .

**Pull request closed without merging**
