### PR TITLE
Enhancement/deprecated jquery

### PR DESCRIPTION
**Pull request by absolutelynotjames**
Addresses #473 

- Tested against jquery-migrate 3.1

- jquery-migrate still complains about $.unique(), I think because it's used internally by $.find() in the 1.x branch of jquery?

Please let me know if anything doesn't look quite right or if there's anything I could have done better!

Thanks!

### CODE REVIEW

**Comment by johnbillion** [comment]
Thanks for the PR! I'll try to find some time over the next week or so to review.

**Comment by johnbillion** [comment]
@absolutelynotjames Thanks again for the PR.

There seems to be a problem with your branch and I'm not sure exactly what it is. I think your branch is somehow detached from the main tree. I'll try to find some time to figure it out.

In the meantime: The second of these three commits adds a bunch of changes which will break QM because they're removing calls which trigger an event. Do you have some time to correct these? Let me know. The main correction is that they need to call `{element}.trigger( {event} )` rather than adding an event handler.

**Comment by absolutelynotjames** [comment]
@johnbillion - Thanks for the feedback, sounds straightforward. I'll take a look and work to get these resolved!

**Comment by absolutelynotjames** [comment]
Thanks again for flagging those mistakes in my code - now that I'm looking at it that was kind of a silly mistake. I changed all of the .on() methods to .trigger() as they should be. I did a run through test of all the button/select elements on my local dev copy and I think everything seems to work as expected.

I also tried to bring my branch up to date with yours, and included that merge in a squashed commit. I hope this helps, but I see there are a couple of merge conflicts.

Let me know if anything else looks off or if there's anything else I can do about my branch deviating from the main tree.

Thanks!

**Comment by johnbillion** [comment]
Thanks again for those updates James. I'm not sure what's up with your branch, but it's completely detached from the main tree:



I think your best bet here is to start again from the develop branch and re-commit those changes without squashing or rebasing, otherwise you'll still have a detached branch.

**Pull request closed without merging**
