### PR TITLE
Improve QM_Output_Html

### PR DESCRIPTION
**Pull request by szepeviktor**
These changes have no name!
Maybe "Adding new PHP features"?

### CODE REVIEW

**Comment by szepeviktor** [comment]
Having no templating system in WordPress makes me sad
... or use Timber.

**Comment by szepeviktor** [comment]
> Mixing programming languages

John! A new section in https://github.com/szepeviktor/very-clean-code 🎉 

## 🔴 Mixing programming languages

Make low-level libraries connect different languages.

- PHP + SQL: ORM
- PHP + HTML: template engine
- PHP + JavaScript: JSON
- PHP + CSS: use CSS classes and variables

**Comment by crstauf** [comment]
I'm personally not a fan of ternary operators, as it makes code less clear and reading and comprehension slower, especially for junior developers.

**Comment by szepeviktor** [comment]
> especially for junior developers

I agree with you.
If I see a ⚠️ warning: _Junior Developers_ I quickly run away 🐰

**Comment by johnbillion** [comment]
Thanks for the PR Viktor but I'm going to close this off as I'm trying to minimise non-functional changes at the moment. Cheers!

**Comment by szepeviktor** [comment]
Okay. I'm a non-functional change generator.

**Pull request closed without merging**
